insert into `currency` (`code`, `countryName`, `name`) values
    ('AED',	'United Arab Emirates',	'UAE Dirham'),
    ('AFN',	'Afghanistan',	'Afghan Afghani'),
    ('ALL',	'Albania',	'Albanian Lek'),
    ('AMD',	'Armenia',	'Armenian Dram'),
    ('ANG',	'Netherlands Antilles',	'Netherlands Antillian Guilder'),
    ('AOA',	'Angola',	'Angolan Kwanza'),
    ('ARS',	'Argentina',	'Argentine Peso'),
    ('AUD',	'Australia',	'Australian Dollar'),
    ('AWG',	'Aruba',	'Aruban Florin'),
    ('AZN',	'Azerbaijan',	'Azerbaijani Manat'),
    ('BAM',	'Bosnia and Herzegovina',	'Bosnia and Herzegovina Mark'),
    ('BBD',	'Barbados',	'Barbados Dollar'),
    ('BDT',	'Bangladesh',	'Bangladeshi Taka'),
    ('BGN',	'Bulgaria',	'Bulgarian Lev'),
    ('BHD',	'Bahrain',	'Bahraini Dinar'),
    ('BIF',	'Burundi',	'Burundian Franc'),
    ('BMD',	'Bermuda',	'Bermudian Dollar'),
    ('BND',	'Brunei',	'Brunei Dollar'),
    ('BOB',	'Bolivia',	'Bolivian Boliviano'),
    ('BRL',	'Brazil',	'Brazilian Real'),
    ('BSD',	'Bahamas',	'Bahamian Dollar'),
    ('BTN',	'Bhutan',	'Bhutanese Ngultrum'),
    ('BWP',	'Botswana',	'Botswana Pula'),
    ('BYN',	'Belarus',	'Belarusian Ruble'),
    ('BZD',	'Belize',	'Belize Dollar'),
    ('CAD',	'Canada',	'Canadian Dollar'),
    ('CDF',	'Democratic Republic of the Congo',	'Congolese Franc'),
    ('CHF',	'Switzerland',	'Swiss Franc'),
    ('CLP',	'Chile',	'Chilean Peso'),
    ('CNY',	'China',	'Chinese Renminbi'),
    ('COP',	'Colombia',	'Colombian Peso'),
    ('CRC',	'Costa Rica',	'Costa Rican Colon'),
    ('CUP',	'Cuba',	'Cuban Peso'),
    ('CVE',	'Cape Verde',	'Cape Verdean Escudo'),
    ('CZK',	'Czech Republic',	'Czech Koruna'),
    ('DJF',	'Djibouti',	'Djiboutian Franc'),
    ('DKK',	'Denmark',	'Danish Krone'),
    ('DOP',	'Dominican Republic',	'Dominican Peso'),
    ('DZD',	'Algeria',	'Algerian Dinar'),
    ('EGP',	'Egypt',	'Egyptian Pound'),
    ('ERN',	'Eritrea',	'Eritrean Nakfa'),
    ('ETB',	'Ethiopia',	'Ethiopian Birr'),
    ('EUR',	'European Union',	'Euro'),
    ('FJD',	'Fiji',	'Fiji Dollar'),
    ('FKP',	'Falkland Islands',	'Falkland Islands Pound'),
    ('FOK',	'Faroe Islands',	'Faroese Króna'),
    ('GBP',	'United Kingdom',	'Pound Sterling'),
    ('GEL',	'Georgia',	'Georgian Lari'),
    ('GGP',	'Guernsey',	'Guernsey Pound'),
    ('GHS',	'Ghana',	'Ghanaian Cedi'),
    ('GIP',	'Gibraltar',	'Gibraltar Pound'),
    ('GMD',	'The Gambia',	'Gambian Dalasi'),
    ('GNF',	'Guinea',	'Guinean Franc'),
    ('GTQ',	'Guatemala',	'Guatemalan Quetzal'),
    ('GYD',	'Guyana',	'Guyanese Dollar'),
    ('HKD',	'Hong Kong',	'Hong Kong Dollar'),
    ('HNL',	'Honduras',	'Honduran Lempira'),
    ('HRK',	'Croatia',	'Croatian Kuna'),
    ('HTG',	'Haiti',	'Haitian Gourde'),
    ('HUF',	'Hungary',	'Hungarian Forint'),
    ('IDR',	'Indonesia',	'Indonesian Rupiah'),
    ('ILS',	'Israel',	'Israeli New Shekel'),
    ('IMP',	'Isle of Man',	'Manx Pound'),
    ('INR',	'India',	'Indian Rupee'),
    ('IQD',	'Iraq',	'Iraqi Dinar'),
    ('IRR',	'Iran',	'Iranian Rial'),
    ('ISK',	'Iceland',	'Icelandic Króna'),
    ('JEP',	'Jersey',	'Jersey Pound'),
    ('JMD',	'Jamaica',	'Jamaican Dollar'),
    ('JOD',	'Jordan',	'Jordanian Dinar'),
    ('JPY',	'Japan',	'Japanese Yen'),
    ('KES',	'Kenya',	'Kenyan Shilling'),
    ('KGS',	'Kyrgyzstan',	'Kyrgyzstani Som'),
    ('KHR',	'Cambodia',	'Cambodian Riel'),
    ('KID',	'Kiribati',	'Kiribati Dollar'),
    ('KMF',	'Comoros',	'Comorian Franc'),
    ('KRW',	'South Korea',	'South Korean Won'),
    ('KWD',	'Kuwait',	'Kuwaiti Dinar'),
    ('KYD',	'Cayman Islands',	'Cayman Islands Dollar'),
    ('KZT',	'Kazakhstan',	'Kazakhstani Tenge'),
    ('LAK',	'Laos',	'Lao Kip'),
    ('LBP',	'Lebanon',	'Lebanese Pound'),
    ('LKR',	'Sri Lanka',	'Sri Lanka Rupee'),
    ('LRD',	'Liberia',	'Liberian Dollar'),
    ('LSL',	'Lesotho',	'Lesotho Loti'),
    ('LYD',	'Libya',	'Libyan Dinar'),
    ('MAD',	'Morocco',	'Moroccan Dirham'),
    ('MDL',	'Moldova',	'Moldovan Leu'),
    ('MGA',	'Madagascar',	'Malagasy Ariary'),
    ('MKD',	'North Macedonia',	'Macedonian Denar'),
    ('MMK',	'Myanmar',	'Burmese Kyat'),
    ('MNT',	'Mongolia',	'Mongolian Tögrög'),
    ('MOP',	'Macau',	'Macanese Pataca'),
    ('MRU',	'Mauritania',	'Mauritanian Ouguiya'),
    ('MUR',	'Mauritius',	'Mauritian Rupee'),
    ('MVR',	'Maldives',	'Maldivian Rufiyaa'),
    ('MWK',	'Malawi',	'Malawian Kwacha'),
    ('MXN',	'Mexico',	'Mexican Peso'),
    ('MYR',	'Malaysia',	'Malaysian Ringgit'),
    ('MZN',	'Mozambique',	'Mozambican Metical'),
    ('NAD',	'Namibia',	'Namibian Dollar'),
    ('NGN',	'Nigeria',	'Nigerian Naira'),
    ('NIO',	'Nicaragua',	'Nicaraguan Córdoba'),
    ('NOK',	'Norway',	'Norwegian Krone'),
    ('NPR',	'Nepal',	'Nepalese Rupee'),
    ('NZD',	'New Zealand',	'New Zealand Dollar'),
    ('OMR',	'Oman',	'Omani Rial'),
    ('PAB',	'Panama',	'Panamanian Balboa'),
    ('PEN',	'Peru',	'Peruvian Sol'),
    ('PGK',	'Papua New Guinea',	'Papua New Guinean Kina'),
    ('PHP',	'Philippines',	'Philippine Peso'),
    ('PKR',	'Pakistan',	'Pakistani Rupee'),
    ('PLN',	'Poland',	'Polish Złoty'),
    ('PYG',	'Paraguay',	'Paraguayan Guaraní'),
    ('QAR',	'Qatar',	'Qatari Riyal'),
    ('RON',	'Romania',	'Romanian Leu'),
    ('RSD',	'Serbia',	'Serbian Dinar'),
    ('RUB',	'Russia',	'Russian Ruble'),
    ('RWF',	'Rwanda',	'Rwandan Franc'),
    ('SAR',	'Saudi Arabia',	'Saudi Riyal'),
    ('SBD',	'Solomon Islands',	'Solomon Islands Dollar'),
    ('SCR',	'Seychelles',	'Seychellois Rupee'),
    ('SDG',	'Sudan',	'Sudanese Pound'),
    ('SEK',	'Sweden',	'Swedish Krona'),
    ('SGD',	'Singapore',	'Singapore Dollar'),
    ('SHP',	'Saint Helena',	'Saint Helena Pound'),
    ('SLE',	'Sierra Leone',	'Sierra Leonean Leone'),
    ('SOS',	'Somalia',	'Somali Shilling'),
    ('SRD',	'Suriname',	'Surinamese Dollar'),
    ('SSP',	'South Sudan',	'South Sudanese Pound'),
    ('STN',	'São Tomé and Príncipe',	'São Tomé and Príncipe Dobra'),
    ('SYP',	'Syria',	'Syrian Pound'),
    ('SZL',	'Eswatini',	'Eswatini Lilangeni'),
    ('THB',	'Thailand',	'Thai Baht'),
    ('TJS',	'Tajikistan',	'Tajikistani Somoni'),
    ('TMT',	'Turkmenistan',	'Turkmenistan Manat'),
    ('TND',	'Tunisia',	'Tunisian Dinar'),
    ('TOP',	'Tonga',	'Tongan Paʻanga'),
    ('TRY',	'Turkey',	'Turkish Lira'),
    ('TTD',	'Trinidad and Tobago',	'Trinidad and Tobago Dollar'),
    ('TVD',	'Tuvalu',	'Tuvaluan Dollar'),
    ('TWD',	'Taiwan',	'New Taiwan Dollar'),
    ('TZS',	'Tanzania',	'Tanzanian Shilling'),
    ('UAH',	'Ukraine',	'Ukrainian Hryvnia'),
    ('UGX',	'Uganda',	'Ugandan Shilling'),
    ('USD',	'United States',	'United States Dollar'),
    ('UYU',	'Uruguay',	'Uruguayan Peso'),
    ('UZS',	'Uzbekistan',	'Uzbekistani So\'m'),
    ('VES',	'Venezuela',	'Venezuelan Bolívar Soberano'),
    ('VND',	'Vietnam',	'Vietnamese Đồng'),
    ('VUV',	'Vanuatu',	'Vanuatu Vatu'),
    ('WST',	'Samoa',	'Samoan Tālā'),
    ('XAF',	'CEMAC',	'Central African CFA Franc'),
    ('XCD',	'Organisation of Eastern Caribbean States',	'East Caribbean Dollar'),
    ('XDR',	'International Monetary Fund',	'Special Drawing Rights'),
    ('XOF',	'CFA',	'West African CFA franc'),
    ('XPF',	'Collectivités d\'Outre-Mer',	'CFP Franc'),
    ('YER',	'Yemen',	'Yemeni Rial'),
    ('ZAR',	'South Africa',	'South African Rand'),
    ('ZMW',	'Zambia',	'Zambian Kwacha'),
    ('ZWL',	'Zimbabwe',	'Zimbabwean Dollar');